// GenAI v8.0.15 - Route Generator
// Generates Express.js routes with Joi validation

const fs = require('fs');
const path = require('path');

class GenSrc {
  constructor(config) {
    this.config = config;
    this.componentName = config.componentName || 'Component';
    this.usecaseName = config.usecaseName || 'usecase';
    this.comId = config.comId || 'com_id:0000';
    this.fields = config.fields || [];
    this.version = config.version || 'v8.0.15';
  }

  generateFieldValidation(field, isRequired = true) {
    let validation = `Joi.${field.type}()`;
    
    if (field.maxLength) {
      validation += `.max(${field.maxLength})`;
    }
    
    if (field.allowNull) {
      validation += `.allow(null).allow("")`;
    }
    
    if (isRequired && field.required) {
      validation += `.required()`;
    } else {
      validation += `.optional()`;
    }
    
    return validation;
  }

  generateSchemaFields(indent = '          ', isRequired = true) {
    return this.fields.map(field => {
      const validation = this.generateFieldValidation(field, isRequired);
      return `${indent}${field.name}: ${validation},`;
    }).join('\n');
  }

  generateRouteFile() {
    const className = `${this.componentName}Routes`;
    
    return `// this source generated by GenAI ${this.version}
// MS Com ID: ${this.comId}

const router = require("express").Router();
const Joi = require("@hapi/joi");

class ${className} {
  constructor(${this.usecaseName}) {
    this.${this.usecaseName} = ${this.usecaseName};
    this.init();
  }

  init() {
    router.post("/insertRecord", async (req, res) => {
      try {
        const schema = {
${this.generateSchemaFields()}
        };

        const record = req.body;
        const isValid = Joi.validate(record, schema);

        if (isValid.error !== null) {
          console.log(isValid.error);
          throw isValid.error;
        }
        record.decoded = req.decoded;
        const { code, id } = await this.${this.usecaseName}.insertRecord(record);
        res.json({ code: code, id: id });
      } catch (err) {
        if (err.name === "ValidationError") {
          res.json({ code: 422, msg: err.toString() });
        } else {
          console.log(err);
          res.json({ code: 500, msg: err.toString() });
        }
      }
      res.end();
    });

    router.post("/insertMulti", async (req, res) => {
      try {
        const schema = {
          arr_${this.componentName}Helper: Joi.array().allow(
            Joi.object({
${this.generateSchemaFields('              ')}
            })
          ),
        };

        const record = req.body;
        const isValid = Joi.validate(record, schema);

        if (isValid.error !== null) {
          console.log(isValid.error);
          throw isValid.error;
        }

        const { code, id } = await this.${this.usecaseName}.insertMulti(record);
        res.json({ code: code, id: id });
      } catch (err) {
        if (err.name === "ValidationError") {
          res.json({ code: 422, msg: err.toString() });
        } else {
          console.log(err);
          res.json({ code: 500, msg: err.toString() });
        }
      }
      res.end();
    });

    router.patch("/updateRecord", async (req, res) => {
      try {
        const schema = {
          id: Joi.number().required(),
          is_active: Joi.string().required(),
${this.generateSchemaFields('          ', false)}
        };

        const data = req.body;

        const isValid = Joi.validate(data, schema);

        if (isValid.error !== null) {
          throw isValid.error;
        }
        data.decoded = req.decoded;
        const log = await this.${this.usecaseName}.updateRecord(data);
        res.json({ code: log });
      } catch (err) {
        if (err.name === "ValidationError") {
          res.json({ code: 422, msg: err.toString() });
        } else {
          res.json({ code: 500, msg: err.toString() });
        }
      }
      res.end();
    });

    router.get("/getPageDet", async (req, res) => {
      try {
        const filter = req.query;
        filter.decoded = req.decoded;
        const data = await this.${this.usecaseName}.getPageDet(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

    router.get("/getRecord", async (req, res) => {
      try {
        const filter = req.query;
        const data = await this.${this.usecaseName}.getRecord(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

    router.get("/getMPageDet", async (req, res) => {
      try {
        const filter = req.query;
        filter.decoded = req.decoded;
        const data = await this.${this.usecaseName}.getMPageDet(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

    router.get("/getMRecord", async (req, res) => {
      try {
        const filter = req.query;
        const data = await this.${this.usecaseName}.getMRecord(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

    router.get("/getRecordForOrder", async (req, res) => {
      try {
        const filter = req.query;
        const data = await this.${this.usecaseName}.getRecordForOrder(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: 500, msg: "An error occurred !" });
      }
      res.end();
    });

    router.get("/getFilteredData", async (req, res) => {
      try {
        const filter = req.query;
        filter.decoded = req.decoded;
        const data = await this.${this.usecaseName}.getFilteredData(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

    router.get("/getAudit", async (req, res) => {
      try {
        const filter = req.query;
        filter.decoded = req.decoded;
        const data = await this.${this.usecaseName}.getAudit(filter);
        res.json(data);
      } catch (err) {
        res.json({ code: err.name === "ValidationError" ? 422 : 500, msg: err.toString() });
      }
      res.end();
    });

  }
  getRouter() {
    return router;
  }
}

module.exports = (${this.usecaseName}) => {
  return new ${this.componentName}(${this.usecaseName});
};
`;
  }

  writeToFile(outputPath) {
    const content = this.generateRouteFile();
    fs.writeFileSync(outputPath, content, 'utf8');
    console.log(`✓ Generated route file: ${outputPath}`);
  }
}

// Example usage and CLI interface
if (require.main === module) {
  // Example configuration matching your provided code
  const exampleConfig = {
    componentName: 'taMSDetV8',
    usecaseName: 'taMSDetV8Usecase',
    comId: 'com_id:4001',
    version: 'v8.0.15',
    fields: [
      { name: 'clt_ref_id', type: 'string', maxLength: 20, allowNull: true, required: false },
      { name: 'ms_name', type: 'string', maxLength: 20, required: true },
      { name: 'ms_id', type: 'number', required: true },
      { name: 'is_comments', type: 'number', required: true },
      { name: 'parent_id', type: 'number', allowNull: true, required: false },
      { name: 'is_active', type: 'string', maxLength: 20, required: true },
      { name: 'created_at', type: 'date', allowNull: true, required: false },
      { name: 'created_by', type: 'string', maxLength: 50, required: true },
      { name: 'last_upd_at', type: 'date', allowNull: true, required: false },
      { name: 'last_upd_by', type: 'string', maxLength: 100, allowNull: true, required: false },
      { name: 'tnnt_id', type: 'number', required: true },
      { name: 'lc_status_id', type: 'number', required: true }
    ]
  };

  const generator = new GenSrc(exampleConfig);
  const outputPath = path.join(__dirname, 'generated-routes.js');
  generator.writeToFile(outputPath);
  
  console.log('\n📝 Example usage:');
  console.log('const GenSrc = require("./gensrc");');
  console.log('const config = { componentName: "MyComponent", usecaseName: "myUsecase", fields: [...] };');
  console.log('const generator = new GenSrc(config);');
  console.log('generator.writeToFile("./output/routes.js");');
}

module.exports = GenSrc;
